name: Build, Sign, and Release

on:
  push:
    branches:
      - main

jobs:
  build-windows:
    name: Build for Windows
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Quasar dependencies
        working-directory: ./FrontEnd
        run: npm install

      - name: Install Electron dependencies
        working-directory: ./FrontEnd/src-electron
        run: npm install

      - name: Build Windows executable
        working-directory: ./FrontEnd
        run: npx quasar build -m electron -T win32 -A x64

      - name: Upload Windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: TruCar-Windows-Build
          path: ./FrontEnd/dist/electron/Packaged/TruCar-win32-x64

  build-android:
    name: Build for Android
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup Java (JDK)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Install Quasar dependencies
        working-directory: ./FrontEnd
        run: npm install

      - name: Build Capacitor assets
        working-directory: ./FrontEnd
        run: npx quasar build -m capacitor -T android

      - name: Decode Keystore
        working-directory: ./FrontEnd/src-capacitor/android
        run: echo "${{ secrets.KEYSTORE_FILE_B64 }}" | base64 --decode > ./keystore.jks

      - name: Build APK and AAB
        working-directory: ./FrontEnd/src-capacitor/android
        run: |
          ./gradlew assembleRelease -Pandroid.injected.signing.store.file=$(pwd)/keystore.jks -Pandroid.injected.signing.store.password=${{ secrets.KEYSTORE_PASSWORD }} -Pandroid.injected.signing.key.alias=${{ secrets.KEY_ALIAS }} -Pandroid.injected.signing.key.password=${{ secrets.KEY_PASSWORD }}
          ./gradlew bundleRelease -Pandroid.injected.signing.store.file=$(pwd)/keystore.jks -Pandroid.injected.signing.store.password=${{ secrets.KEYSTORE_PASSWORD }} -Pandroid.injected.signing.key.alias=${{ secrets.KEY_ALIAS }} -Pandroid.injected.signing.key.password=${{ secrets.KEY_PASSWORD }}

      - name: Upload Android artifacts
        uses: actions/upload-artifact@v4
        with:
          name: TruCar-Android-Builds
          path: |
            ./FrontEnd/src-capacitor/android/app/build/outputs/apk/release/app-release.apk
            ./FrontEnd/src-capacitor/android/app/build/outputs/bundle/release/app-release.aab

  create-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: [build-windows, build-android]
    permissions:
      contents: write
    steps:
      - name: Download Windows artifact
        uses: actions/download-artifact@v4
        with:
          name: TruCar-Windows-Build
          path: ./release-assets/windows

      - name: Download Android artifacts
        uses: actions/download-artifact@v4
        with:
          name: TruCar-Android-Builds
          path: ./release-assets/android

      - name: Checkout code (for source zip)
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Create source code zip
        run: zip -r source-code.zip . -x ".git/*"

      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: TruCar ${{ github.ref_name }}
          body: "Release automática gerada pelo GitHub Actions."
          files: |
            ./release-assets/windows/*
            ./release-assets/android/*
            source-code.zip
